targets:
  Eber:
    type: application
    platform: iOS
    sources:
      - path: ./Sources
      - path: ./Resources
      - path: ./Resources/R.generated.swift
        optional: true

    dependencies:
      - sdk: Foundation.framework
      - sdk: UIKit.framework

    preBuildScripts:
      - path: /bin/sh
        name: Run R.swift
        inputFiles:
          - $TEMP_DIR/rswift-lastrun
        outputFiles:
          - $SRCROOT/Projects/Eber/Resources/R.generated.swift
        script: |
          "$PODS_ROOT/R.swift/rswift" generate "$SRCROOT/Projects/Eber/Resources/R.generated.swift"

    settings:
      PRODUCT_NAME: Eber
      PRODUCT_BUNDLE_IDENTIFIER: $(PRODUCT_NAME)
      INFOPLIST_FILE: "$(SRCROOT)/Projects/Eber/Supporting Files/Info.plist"

  EberTests:
    templates: [UnitTest]
    templateAttributes:
      testTarget: Eber

schemes:
  Eber:
    build:
      targets:
        Eber: all
        EberTests: [test]
    run:
      environmentVariables:
        OS_ACTIVITY_MODE: disable
    test:
      gatherCoverageData: true
      targets: [EberTests]
